name 'kernelcare'
maintainer 'Rinat Sabitov'
maintainer_email 'rsabitov@cloudlinux.com'
license 'Apache-2.0'
description 'Installs/Configures Kernelcare'

version '0.1.6'
chef_version '>= 14.0'
source_url 'https://github.com/cloudlinux/kcare-chef'
issues_url 'https://github.com/cloudlinux/kcare-chef/issues'

supports 'amazon'
supports 'centos'
supports 'oracle'
supports 'debian'
supports 'redhat'
supports 'ubuntu'
